// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from "eslint-plugin-storybook";

import js from '@eslint/js';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';

export default [{
  ignores: [
    '.next/**',
    '.next-previous/**',
    '.swc/**',
    'node_modules/**',
    '.legacy/**',
    'coverage/**',
    '**/*.d.ts',
    'public/**',
    'postcss.config.js',
    'tailwind.config.ts',
    'scripts/**',
    '__tests__/**',
    '__mocks__/**',
    'storybook-static/**',
    '.agents/**',
    '.claude/**',
    '.impeccable/**',
    'fixroast/**',
    'test-results/**',
    'ux-audit-evidence/**',
    'plans/**',
    'docs/**',
    'e2e/**',
  ],
}, js.configs.recommended, {
  files: ['**/*.{ts,tsx}'],
  languageOptions: {
    parser: typescriptParser,
    parserOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      ecmaFeatures: {
        jsx: true,
      },
    },
    globals: {
      console: 'readonly',
      process: 'readonly',
      Buffer: 'readonly',
      __dirname: 'readonly',
      __filename: 'readonly',
      module: 'readonly',
      require: 'readonly',
      exports: 'writable',
      URL: 'readonly',
      URLSearchParams: 'readonly',
      fetch: 'readonly',
      Request: 'readonly',
      Response: 'readonly',
      Headers: 'readonly',
      FormData: 'readonly',
      File: 'readonly',
      Blob: 'readonly',
      AbortController: 'readonly',
      setTimeout: 'readonly',
      clearTimeout: 'readonly',
      setInterval: 'readonly',
      clearInterval: 'readonly',
      setImmediate: 'readonly',
      clearImmediate: 'readonly',
      globalThis: 'readonly',
      window: 'readonly',
      document: 'readonly',
      navigator: 'readonly',
      localStorage: 'readonly',
      sessionStorage: 'readonly',
      location: 'readonly',
      history: 'readonly',
      alert: 'readonly',
      confirm: 'readonly',
      prompt: 'readonly',
      Event: 'readonly',
      CustomEvent: 'readonly',
      Element: 'readonly',
      HTMLElement: 'readonly',
      EventListener: 'readonly',
      EventTarget: 'readonly',
    },
  },
  plugins: {
    '@typescript-eslint': typescript,
  },
  rules: {
    ...typescript.configs.recommended.rules,
    '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-require-imports': 'off',
    'no-unused-vars': 'off',
    'no-undef': 'off',
  },
}, ...storybook.configs["flat/recommended"]];
