// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/7-systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/7-systems">> = Specific
  const handler = {} as typeof import("../../app/7-systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about/team">> = Specific
  const handler = {} as typeof import("../../app/about/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/accessible-nebula/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accessible-nebula">> = Specific
  const handler = {} as typeof import("../../app/accessible-nebula/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-burn-leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ad-burn-leaderboard">> = Specific
  const handler = {} as typeof import("../../app/ad-burn-leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ads-getting-clicks-but-no-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads-getting-clicks-but-no-sales">> = Specific
  const handler = {} as typeof import("../../app/ads-getting-clicks-but-no-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agency-partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency-partner">> = Specific
  const handler = {} as typeof import("../../app/agency-partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai-ops-retainer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-ops-retainer">> = Specific
  const handler = {} as typeof import("../../app/ai-ops-retainer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai-sdr-vs-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-sdr-vs-audit">> = Specific
  const handler = {} as typeof import("../../app/ai-sdr-vs-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-dashboard">> = Specific
  const handler = {} as typeof import("../../app/audit-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-lander/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-lander">> = Specific
  const handler = {} as typeof import("../../app/audit-lander/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/[id]/processing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/[id]/processing">> = Specific
  const handler = {} as typeof import("../../app/audit/[id]/processing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/[id]/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/[id]/results">> = Specific
  const handler = {} as typeof import("../../app/audit/[id]/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/compare">> = Specific
  const handler = {} as typeof import("../../app/audit/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/results">> = Specific
  const handler = {} as typeof import("../../app/audit/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/sample/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit/sample">> = Specific
  const handler = {} as typeof import("../../app/audit/sample/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audits">> = Specific
  const handler = {} as typeof import("../../app/audits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/best-landing-page-audit-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/best-landing-page-audit-tools">> = Specific
  const handler = {} as typeof import("../../app/best-landing-page-audit-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beta-tester/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beta-tester">> = Specific
  const handler = {} as typeof import("../../app/beta-tester/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand">> = Specific
  const handler = {} as typeof import("../../app/brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies/[slug]">> = Specific
  const handler = {} as typeof import("../../app/case-studies/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout-impulse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout-impulse">> = Specific
  const handler = {} as typeof import("../../app/checkout-impulse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout-v2">> = Specific
  const handler = {} as typeof import("../../app/checkout-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/about">> = Specific
  const handler = {} as typeof import("../../app/company/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/team">> = Specific
  const handler = {} as typeof import("../../app/company/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare/[slug]">> = Specific
  const handler = {} as typeof import("../../app/compare/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/component-showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/component-showcase">> = Specific
  const handler = {} as typeof import("../../app/component-showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/concepts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/concepts">> = Specific
  const handler = {} as typeof import("../../app/concepts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create-97-checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-97-checkout">> = Specific
  const handler = {} as typeof import("../../app/create-97-checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cta-optimization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cta-optimization">> = Specific
  const handler = {} as typeof import("../../app/cta-optimization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-rights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-rights">> = Specific
  const handler = {} as typeof import("../../app/data-rights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ecommerce-landing-page-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ecommerce-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/ecommerce-landing-page-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/editorial-standards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/editorial-standards">> = Specific
  const handler = {} as typeof import("../../app/editorial-standards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fix-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fix-library">> = Specific
  const handler = {} as typeof import("../../app/fix-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/for/[vertical]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/for/[vertical]">> = Specific
  const handler = {} as typeof import("../../app/for/[vertical]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/funnel-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/funnel-audit">> = Specific
  const handler = {} as typeof import("../../app/funnel-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/generator">> = Specific
  const handler = {} as typeof import("../../app/generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-launch-confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-launch-confirmation">> = Specific
  const handler = {} as typeof import("../../app/growth-launch-confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/growth-launch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/growth-launch">> = Specific
  const handler = {} as typeof import("../../app/growth-launch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/headline-optimization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/headline-optimization">> = Specific
  const handler = {} as typeof import("../../app/headline-optimization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/index-old/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/index-old">> = Specific
  const handler = {} as typeof import("../../app/index-old/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab">> = Specific
  const handler = {} as typeof import("../../app/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing-page-audit-tools-pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-page-audit-tools-pricing">> = Specific
  const handler = {} as typeof import("../../app/landing-page-audit-tools-pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing-page-cta-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-page-cta-audit">> = Specific
  const handler = {} as typeof import("../../app/landing-page-cta-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing-page-message-match/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-page-message-match">> = Specific
  const handler = {} as typeof import("../../app/landing-page-message-match/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing-page-mistakes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-page-mistakes">> = Specific
  const handler = {} as typeof import("../../app/landing-page-mistakes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing-page-trust-signals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing-page-trust-signals">> = Specific
  const handler = {} as typeof import("../../app/landing-page-trust-signals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/launch-page-97/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/launch-page-97">> = Specific
  const handler = {} as typeof import("../../app/launch-page-97/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lead-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lead-dashboard">> = Specific
  const handler = {} as typeof import("../../app/lead-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lead-generation-landing-page-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lead-generation-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/lead-generation-landing-page-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leak-index/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leak-index">> = Specific
  const handler = {} as typeof import("../../app/leak-index/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/above-fold-landing-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/above-fold-landing-page">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/above-fold-landing-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/ad-says-one-thing-page-says-another/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/ad-says-one-thing-page-says-another">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/ad-says-one-thing-page-says-another/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/agency-handoff-debt/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/agency-handoff-debt">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/agency-handoff-debt/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/b2b-saas-landing-page-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/b2b-saas-landing-page-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/b2b-saas-landing-page-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/before-you-raise-ad-budget/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/before-you-raise-ad-budget">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/before-you-raise-ad-budget/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/coach-consultant-landing-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/coach-consultant-landing-page">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/coach-consultant-landing-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/confessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/confessions">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/confessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/cpc-break-even-landing-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/cpc-break-even-landing-page">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/cpc-break-even-landing-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/cta-below-fold-mobile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/cta-below-fold-mobile">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/cta-below-fold-mobile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/cta-not-working/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/cta-not-working">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/cta-not-working/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/ecommerce-landing-page-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/ecommerce-landing-page-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/ecommerce-landing-page-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/facebook-ads-no-leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/facebook-ads-no-leads">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/facebook-ads-no-leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/form-has-zero-friction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/form-has-zero-friction">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/form-has-zero-friction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/ghost-variant-ab-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/ghost-variant-ab-test">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/ghost-variant-ab-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/google-ads-clicks-no-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/google-ads-clicks-no-sales">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/google-ads-clicks-no-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/google-ads-disapproved-ads-still-spending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/google-ads-disapproved-ads-still-spending">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/google-ads-disapproved-ads-still-spending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/google-ads-high-ctr-low-conversion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/google-ads-high-ctr-low-conversion">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/google-ads-high-ctr-low-conversion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/google-ads-quality-score-low/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/google-ads-quality-score-low">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/google-ads-quality-score-low/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/headline-cta-mismatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/headline-cta-mismatch">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/headline-cta-mismatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/high-cpc-low-conversion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/high-cpc-low-conversion">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/high-cpc-low-conversion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/landing-page-bounce-rate-high/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/landing-page-bounce-rate-high">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/landing-page-bounce-rate-high/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/landing-page-conversion-rate-benchmark/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/landing-page-conversion-rate-benchmark">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/landing-page-conversion-rate-benchmark/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/landing-page-intelligence-stack/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/landing-page-intelligence-stack">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/landing-page-intelligence-stack/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/landing-page-load-time-slow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/landing-page-load-time-slow">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/landing-page-load-time-slow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/landing-page-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/landing-page-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/landing-page-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/linkedin-ad-copy-landing-page-mismatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/linkedin-ad-copy-landing-page-mismatch">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/linkedin-ad-copy-landing-page-mismatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/linkedin-ads-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/linkedin-ads-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/linkedin-ads-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/linkedin-authority-gap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/linkedin-authority-gap">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/linkedin-authority-gap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/message-match-checklist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/message-match-checklist">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/message-match-checklist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/meta-ads-high-frequency-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/meta-ads-high-frequency-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/meta-ads-high-frequency-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/mobile-landing-page-leaks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/mobile-landing-page-leaks">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/mobile-landing-page-leaks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/paid-traffic-leak-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/paid-traffic-leak-map">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/paid-traffic-leak-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/pricing-page-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/pricing-page-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/pricing-page-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/proof-before-cta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/proof-before-cta">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/proof-before-cta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/retargeting-ads-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/retargeting-ads-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/retargeting-ads-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/social-proof-backfire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/social-proof-backfire">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/social-proof-backfire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/the-11pm-founder-spiral/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/the-11pm-founder-spiral">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/the-11pm-founder-spiral/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/tiktok-ads-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/tiktok-ads-not-converting">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/tiktok-ads-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/tiktok-landing-page-scroll-speed-gap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/tiktok-landing-page-scroll-speed-gap">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/tiktok-landing-page-scroll-speed-gap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/tiktok-trust-collapse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/tiktok-trust-collapse">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/tiktok-trust-collapse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/traffic-but-no-form-fills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-centre/traffic-but-no-form-fills">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/traffic-but-no-form-fills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketing-ops/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing-ops">> = Specific
  const handler = {} as typeof import("../../app/marketing-ops/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mobile-landing-page-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/mobile-landing-page-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mobile-landing-page-optimization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-landing-page-optimization">> = Specific
  const handler = {} as typeof import("../../app/mobile-landing-page-optimization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/newsletter/confirmed/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/newsletter/confirmed">> = Specific
  const handler = {} as typeof import("../../app/newsletter/confirmed/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/newsletter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/newsletter">> = Specific
  const handler = {} as typeof import("../../app/newsletter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/og-card-source/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/og-card-source">> = Specific
  const handler = {} as typeof import("../../app/og-card-source/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization">> = Specific
  const handler = {} as typeof import("../../app/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page-speed-conversion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/page-speed-conversion">> = Specific
  const handler = {} as typeof import("../../app/page-speed-conversion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/paid-traffic-leak-scorecard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/paid-traffic-leak-scorecard">> = Specific
  const handler = {} as typeof import("../../app/paid-traffic-leak-scorecard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/part-after/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-after">> = Specific
  const handler = {} as typeof import("../../app/part-after/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/part-before/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/part-before">> = Specific
  const handler = {} as typeof import("../../app/part-before/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/founder-second-brain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks/founder-second-brain">> = Specific
  const handler = {} as typeof import("../../app/playbooks/founder-second-brain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/linkedin-skill-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks/linkedin-skill-engine">> = Specific
  const handler = {} as typeof import("../../app/playbooks/linkedin-skill-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks">> = Specific
  const handler = {} as typeof import("../../app/playbooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/specialist-ai-agent-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks/specialist-ai-agent-library">> = Specific
  const handler = {} as typeof import("../../app/playbooks/specialist-ai-agent-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/press/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/press">> = Specific
  const handler = {} as typeof import("../../app/press/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing-guides/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing-guides/[slug]">> = Specific
  const handler = {} as typeof import("../../app/pricing-guides/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/proof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/proof">> = Specific
  const handler = {} as typeof import("../../app/proof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/repair-sprint/example/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repair-sprint/example">> = Specific
  const handler = {} as typeof import("../../app/repair-sprint/example/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/repair-sprint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/repair-sprint">> = Specific
  const handler = {} as typeof import("../../app/repair-sprint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/research/landing-page-performance-q3-2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research/landing-page-performance-q3-2026">> = Specific
  const handler = {} as typeof import("../../app/research/landing-page-performance-q3-2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable/compare">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable/generator">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/jobs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable/jobs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/jobs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/quick-start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable/quick-start">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/quick-start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/citable/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources/citable/releases">> = Specific
  const handler = {} as typeof import("../../app/resources/citable/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roas-cliff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roas-cliff">> = Specific
  const handler = {} as typeof import("../../app/roas-cliff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roi-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roi-calculator">> = Specific
  const handler = {} as typeof import("../../app/roi-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/saas-landing-page-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saas-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/saas-landing-page-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/score/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/score">> = Specific
  const handler = {} as typeof import("../../app/score/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shared/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shared/[token]">> = Specific
  const handler = {} as typeof import("../../app/shared/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/social-proof-landing-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social-proof-landing-page">> = Specific
  const handler = {} as typeof import("../../app/social-proof-landing-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscription">> = Specific
  const handler = {} as typeof import("../../app/subscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teardowns/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teardowns/[slug]">> = Specific
  const handler = {} as typeof import("../../app/teardowns/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/teardowns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teardowns">> = Specific
  const handler = {} as typeof import("../../app/teardowns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/thank-you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thank-you">> = Specific
  const handler = {} as typeof import("../../app/thank-you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/vs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vs">> = Specific
  const handler = {} as typeof import("../../app/vs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/what-is-landing-page-audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/what-is-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/what-is-landing-page-audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/why-cro-agencies-dont-work/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/why-cro-agencies-dont-work">> = Specific
  const handler = {} as typeof import("../../app/why-cro-agencies-dont-work/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/why-is-my-landing-page-not-converting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/why-is-my-landing-page-not-converting">> = Specific
  const handler = {} as typeof import("../../app/why-is-my-landing-page-not-converting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[...path]">> = Specific
  const handler = {} as typeof import("../../app/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent/register">> = Specific
  const handler = {} as typeof import("../../app/api/agent/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/funnel-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/funnel-report">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/funnel-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/funnel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/funnel">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/funnel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/[id]/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/[id]/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/audit/[id]/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/audit/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/[id]/share-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/[id]/share-token">> = Specific
  const handler = {} as typeof import("../../app/api/audit/[id]/share-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/audit/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/claim/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/claim">> = Specific
  const handler = {} as typeof import("../../app/api/audit/claim/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/compare">> = Specific
  const handler = {} as typeof import("../../app/api/audit/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/diff/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/diff">> = Specific
  const handler = {} as typeof import("../../app/api/audit/diff/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/email">> = Specific
  const handler = {} as typeof import("../../app/api/audit/email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/lab/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/lab">> = Specific
  const handler = {} as typeof import("../../app/api/audit/lab/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/rewrites/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/rewrites/generate">> = Specific
  const handler = {} as typeof import("../../app/api/audit/rewrites/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/rewrites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/rewrites">> = Specific
  const handler = {} as typeof import("../../app/api/audit/rewrites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/run">> = Specific
  const handler = {} as typeof import("../../app/api/audit/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/schedules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/schedules/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/audit/schedules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/schedules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/schedules">> = Specific
  const handler = {} as typeof import("../../app/api/audit/schedules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/start">> = Specific
  const handler = {} as typeof import("../../app/api/audit/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/stats/benchmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/stats/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/api/audit/stats/benchmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/stats/recent-finding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/stats/recent-finding">> = Specific
  const handler = {} as typeof import("../../app/api/audit/stats/recent-finding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/stats">> = Specific
  const handler = {} as typeof import("../../app/api/audit/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audit/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/unlock">> = Specific
  const handler = {} as typeof import("../../app/api/audit/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/audits/by-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audits/by-email">> = Specific
  const handler = {} as typeof import("../../app/api/audits/by-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/github/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/github/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/github">> = Specific
  const handler = {} as typeof import("../../app/api/auth/github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google/callback">> = Specific
  const handler = {} as typeof import("../../app/api/auth/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/google/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/google">> = Specific
  const handler = {} as typeof import("../../app/api/auth/google/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/magic-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/magic-link">> = Specific
  const handler = {} as typeof import("../../app/api/auth/magic-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/badge/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/badge/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/badge/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/badges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/badges">> = Specific
  const handler = {} as typeof import("../../app/api/badges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/summary">> = Specific
  const handler = {} as typeof import("../../app/api/billing/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bimi/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bimi">> = Specific
  const handler = {} as typeof import("../../app/api/bimi/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/build-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/build-info">> = Specific
  const handler = {} as typeof import("../../app/api/build-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/competitors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/competitors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/competitors/comparison/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors/comparison">> = Specific
  const handler = {} as typeof import("../../app/api/competitors/comparison/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/competitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/competitors">> = Specific
  const handler = {} as typeof import("../../app/api/competitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/data-rights/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-rights/export">> = Specific
  const handler = {} as typeof import("../../app/api/data-rights/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/email/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/process">> = Specific
  const handler = {} as typeof import("../../app/api/email/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exit-intent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exit-intent">> = Specific
  const handler = {} as typeof import("../../app/api/exit-intent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/experiments/[id]/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]/refresh">> = Specific
  const handler = {} as typeof import("../../app/api/experiments/[id]/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/experiments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/experiments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/experiments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/experiments">> = Specific
  const handler = {} as typeof import("../../app/api/experiments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/fix-library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fix-library">> = Specific
  const handler = {} as typeof import("../../app/api/fix-library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ga4/correlation/[auditId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ga4/correlation/[auditId]">> = Specific
  const handler = {} as typeof import("../../app/api/ga4/correlation/[auditId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ga4/properties/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ga4/properties">> = Specific
  const handler = {} as typeof import("../../app/api/ga4/properties/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ga4/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ga4/select">> = Specific
  const handler = {} as typeof import("../../app/api/ga4/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ga4/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ga4/status">> = Specific
  const handler = {} as typeof import("../../app/api/ga4/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/callback">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/connect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/connect">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/connect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/disconnect">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/inspect">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/sitemap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/sitemap">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/sitemap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/status">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gsc/submit-index/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gsc/submit-index">> = Specific
  const handler = {} as typeof import("../../app/api/gsc/submit-index/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/healthz">> = Specific
  const handler = {} as typeof import("../../app/api/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lab-experiments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lab-experiments/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/lab-experiments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lab-experiments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lab-experiments">> = Specific
  const handler = {} as typeof import("../../app/api/lab-experiments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/lead-gen/rb2b-event/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lead-gen/rb2b-event">> = Specific
  const handler = {} as typeof import("../../app/api/lead-gen/rb2b-event/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitors/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitors/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/monitors/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/monitors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitors">> = Specific
  const handler = {} as typeof import("../../app/api/monitors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mpp/audit-compat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mpp/audit-compat">> = Specific
  const handler = {} as typeof import("../../app/api/mpp/audit-compat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mpp/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mpp/audit">> = Specific
  const handler = {} as typeof import("../../app/api/mpp/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/newsletter/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/confirm">> = Specific
  const handler = {} as typeof import("../../app/api/newsletter/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/readyz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/readyz">> = Specific
  const handler = {} as typeof import("../../app/api/readyz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recommendations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/recommendations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/report/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/report/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/report/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shared/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shared">> = Specific
  const handler = {} as typeof import("../../app/api/shared/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/team">> = Specific
  const handler = {} as typeof import("../../app/api/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/timeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/timeline">> = Specific
  const handler = {} as typeof import("../../app/api/timeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/fixes/[auditId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/fixes/[auditId]">> = Specific
  const handler = {} as typeof import("../../app/api/v1/fixes/[auditId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/fixes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/fixes">> = Specific
  const handler = {} as typeof import("../../app/api/v1/fixes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/v1/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1">> = Specific
  const handler = {} as typeof import("../../app/api/v1/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/rb2b/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/rb2b">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/rb2b/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/widget/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/widget/audit">> = Specific
  const handler = {} as typeof import("../../app/api/widget/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/api-keys/[keyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/api-keys/[keyId]">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/api-keys/[keyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/assistant">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/delete-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/delete-account">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/delete-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/dispatch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/dispatch">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/dispatch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/export">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/preferences">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/team/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/team/accept">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/team/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/team">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/workspace/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace/verify">> = Specific
  const handler = {} as typeof import("../../app/api/workspace/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/gone">> = Specific
  const handler = {} as typeof import("../../app/gone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/md/learning-centre/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/md/learning-centre/[slug]">> = Specific
  const handler = {} as typeof import("../../app/md/learning-centre/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/md/teardowns/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/md/teardowns/[slug]">> = Specific
  const handler = {} as typeof import("../../app/md/teardowns/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(breadcrumb)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(breadcrumb)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ad-burn-leaderboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ad-burn-leaderboard">> = Specific
  const handler = {} as typeof import("../../app/ad-burn-leaderboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit-lander/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit-lander">> = Specific
  const handler = {} as typeof import("../../app/audit-lander/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../app/audit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/results/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit/results">> = Specific
  const handler = {} as typeof import("../../app/audit/results/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/audit/sample/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/audit/sample">> = Specific
  const handler = {} as typeof import("../../app/audit/sample/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/company/about">> = Specific
  const handler = {} as typeof import("../../app/company/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/team/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/company/team">> = Specific
  const handler = {} as typeof import("../../app/company/team/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/index-old/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/index-old">> = Specific
  const handler = {} as typeof import("../../app/index-old/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/learning-centre/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/learning-centre">> = Specific
  const handler = {} as typeof import("../../app/learning-centre/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/og-card-source/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/og-card-source">> = Specific
  const handler = {} as typeof import("../../app/og-card-source/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page-speed-conversion/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/page-speed-conversion">> = Specific
  const handler = {} as typeof import("../../app/page-speed-conversion/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/part-after/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/part-after">> = Specific
  const handler = {} as typeof import("../../app/part-after/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/part-before/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/part-before">> = Specific
  const handler = {} as typeof import("../../app/part-before/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/press/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/press">> = Specific
  const handler = {} as typeof import("../../app/press/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/social-proof-landing-page/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/social-proof-landing-page">> = Specific
  const handler = {} as typeof import("../../app/social-proof-landing-page/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/thank-you/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/thank-you">> = Specific
  const handler = {} as typeof import("../../app/thank-you/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unsubscribe/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/unsubscribe/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/what-is-landing-page-audit/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/what-is-landing-page-audit">> = Specific
  const handler = {} as typeof import("../../app/what-is-landing-page-audit/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
