"""Generate a branded audit report PDF with reportlab.

Layout:
  Header   — agency name/logo when set, else Nebula default
  Summary  — big score, grade, URL, audit date
  Findings — one block per finding: label, impact badge, issue, fix
  Footer   — "Generated by Nebula Components"

Text-first design: a remote agency logo is embedded only when it can be
fetched quickly and decoded; otherwise the report falls back to text.
"""

from __future__ import annotations

import io
import urllib.request
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

ACCENT = colors.HexColor("#00c2a0")
DARK = colors.HexColor("#111827")
MUTED = colors.HexColor("#6b7280")
BORDER = colors.HexColor("#e5e7eb")
RED = colors.HexColor("#ef4444")
AMBER = colors.HexColor("#f59e0b")
GREEN = colors.HexColor("#10b981")

S_TITLE = ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=20, textColor=DARK, spaceAfter=2 * mm)
S_SUB = ParagraphStyle("sub", fontName="Helvetica", fontSize=10, textColor=MUTED, spaceAfter=6 * mm)
S_H2 = ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=14, textColor=DARK, spaceBefore=6 * mm, spaceAfter=3 * mm)
S_BODY = ParagraphStyle("body", fontName="Helvetica", fontSize=9.5, textColor=DARK, leading=13)
S_LABEL = ParagraphStyle("label", fontName="Helvetica-Bold", fontSize=8, textColor=MUTED, spaceBefore=2 * mm, spaceAfter=1 * mm)
S_FOOT = ParagraphStyle("foot", fontName="Helvetica", fontSize=8, textColor=MUTED, alignment=1)


def _impact_meta(impact: float) -> tuple[str, colors.Color]:
    if impact >= 8:
        return "CRITICAL", RED
    if impact >= 5:
        return "WARNING", AMBER
    return "ADVISORY", MUTED


def _score_color(score: float) -> colors.Color:
    if score >= 7:
        return GREEN
    if score >= 5:
        return AMBER
    return RED


def _fmt_date(iso: object) -> str:
    if not iso:
        return "—"
    if isinstance(iso, datetime):
        dt = iso
    else:
        try:
            dt = datetime.fromisoformat(str(iso).replace("Z", "+00:00"))
        except ValueError:
            return str(iso)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%B %d, %Y")


def _fetch_logo(url: str) -> Optional[Image]:
    """Best-effort remote logo fetch. Returns None on any failure."""
    try:
        if not url.startswith(("http://", "https://")):
            return None
        req = urllib.request.Request(url, headers={"User-Agent": "NebulaReport/1.0"})
        with urllib.request.urlopen(req, timeout=3) as resp:
            ctype = resp.headers.get("Content-Type", "")
            if "image" not in ctype:
                return None
            data = resp.read(2 * 1024 * 1024)
        img = Image(io.BytesIO(data))
        # Constrain to a 40mm x 14mm box, preserving aspect ratio
        max_w, max_h = 40 * mm, 14 * mm
        ratio = min(max_w / img.imageWidth, max_h / img.imageHeight, 1.0)
        img.drawWidth = img.imageWidth * ratio
        img.drawHeight = img.imageHeight * ratio
        return img
    except Exception:
        return None


def generate_audit_pdf(
    audit_data: dict,
    findings: list,
    agency_name: Optional[str] = None,
    agency_logo_url: Optional[str] = None,
) -> bytes:
    """Render an audit report PDF and return it as bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=16 * mm,
        title=f"Audit Report — {audit_data.get('url', '')}",
        author=agency_name or "Nebula Components",
    )

    score = float(audit_data.get("score") or 0)
    grade = audit_data.get("grade") or "—"
    url = audit_data.get("url") or ""
    date_str = _fmt_date(audit_data.get("completed_at") or audit_data.get("created_at"))

    story: list = []

    # ── Header ────────────────────────────────────────────────────────
    logo = _fetch_logo(agency_logo_url) if agency_logo_url else None
    brand = agency_name or "Nebula Components"
    if logo is not None:
        header = Table(
            [[logo, Paragraph(f"<b>{brand}</b><br/><font size=9 color='#6b7280'>Landing Page Audit Report</font>",
                              ParagraphStyle("hdr", fontName="Helvetica-Bold", fontSize=14, textColor=DARK, leading=17))]],
            colWidths=[45 * mm, None],
        )
        header.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
        story.append(header)
        story.append(Spacer(1, 4 * mm))
    else:
        story.append(Paragraph(brand, S_TITLE))
        story.append(Paragraph("Landing Page Audit Report", S_SUB))

    # ── Score summary ─────────────────────────────────────────────────
    sc = _score_color(score)
    score_style = ParagraphStyle("score", fontName="Helvetica-Bold", fontSize=34, textColor=sc, leading=38)
    meta_style = ParagraphStyle("meta", fontName="Helvetica", fontSize=10, textColor=DARK, leading=14)
    summary = Table(
        [[
            Paragraph(f"{score:g}<font size=16 color='#6b7280'>/10</font>", score_style),
            Paragraph(
                f"<b>Grade:</b> {grade}<br/>"
                f"<b>URL:</b> {url}<br/>"
                f"<b>Audited:</b> {date_str}<br/>"
                f"<b>Findings:</b> {len(findings)}",
                meta_style,
            ),
        ]],
        colWidths=[45 * mm, None],
    )
    summary.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 0.75, BORDER),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f9fafb")),
        ("LEFTPADDING", (0, 0), (-1, -1), 5 * mm),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5 * mm),
        ("TOPPADDING", (0, 0), (-1, -1), 4 * mm),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4 * mm),
    ]))
    story.append(summary)

    # ── Findings ──────────────────────────────────────────────────────
    story.append(Paragraph("Findings", S_H2))
    if not findings:
        story.append(Paragraph("No findings — all signals passed.", S_BODY))
    for i, f in enumerate(findings, 1):
        impact = float(f.get("impact") or 0)
        badge, badge_color = _impact_meta(impact)
        label = f.get("label") or f.get("key") or f"Finding {i}"

        block: list = [
            Paragraph(
                f"<font color='#6b7280' size=8>FINDING {i}</font><br/><b>{label}</b>"
                f"&nbsp;&nbsp;<font color='{badge_color.hexval().replace('0x', '#')}' size=8><b>{badge} · {impact:g}/10</b></font>",
                ParagraphStyle("fl", fontName="Helvetica-Bold", fontSize=11, textColor=DARK, leading=15),
            ),
        ]
        if f.get("issue"):
            block.append(Paragraph("ISSUE", S_LABEL))
            block.append(Paragraph(str(f["issue"]), S_BODY))
        if f.get("fix"):
            block.append(Paragraph("RECOMMENDED FIX", S_LABEL))
            block.append(Paragraph(str(f["fix"]), S_BODY))

        t = Table([[block]], colWidths=[doc.width])
        t.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.75, BORDER),
            ("LINEBEFORE", (0, 0), (0, -1), 2, badge_color),
            ("LEFTPADDING", (0, 0), (-1, -1), 4 * mm),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4 * mm),
            ("TOPPADDING", (0, 0), (-1, -1), 3 * mm),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3 * mm),
        ]))
        story.append(Spacer(1, 2.5 * mm))
        story.append(t)

    # ── Footer ────────────────────────────────────────────────────────
    story.append(Spacer(1, 10 * mm))
    prepared = f"Prepared by {agency_name} · " if agency_name else ""
    story.append(Paragraph(
        f"{prepared}Generated by Nebula Components · nebulacomponents.com",
        S_FOOT,
    ))

    doc.build(story)
    return buf.getvalue()
