var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/team/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11e145c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1n8rcis._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jknp56._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01-xdwe._.js")
R.c("server/chunks/ssr/_1iqm-mz._.js")
R.c("server/chunks/ssr/_1zqwz53._.js")
R.c("server/chunks/ssr/_05k1yv5._.js")
R.c("server/chunks/ssr/app_error_tsx_15zfp7n._.js")
R.c("server/chunks/ssr/app_not-found_tsx_1gi3i27._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/app_global-error_tsx_0w002m_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_about_team_page_actions_04y3xw6.js")
R.m(66888)
module.exports=R.m(66888).exports
