export type Finding = {
  key: string
  label: string
  impact: number
  quadrant: 'Quick Win' | 'Major Project'
  issue: string
  evidence: string
  fix: string
}

export type Teardown = {
  slug: string
  name: string
  url: string
  domain: string
  score: number
  grade: string
  auditedAt: string
  summary: string
  context: string
  findings: Finding[]
  /** Optional OG/screenshot image shown in a browser mockup above the findings. */
  screenshotUrl?: string
}

export const TEARDOWNS: Record<string, Teardown> = {
  basecamp: {
    slug: 'basecamp',
    name: 'Basecamp',
    url: 'https://basecamp.com',
    domain: 'basecamp.com',
    score: 5.4,
    grade: 'C',
    auditedAt: 'July 29, 2026',
    summary: 'Nebula ran its 7-signal audit on basecamp.com. Score: 5.4/10, Grade C. Five specific findings — evidence-backed, not opinions.',
    context: 'Basecamp is a well-run company with a widely-used product. A 5.4/10 is not a verdict on their business — it\'s a snapshot of five specific, measurable page-level conditions the engine flags for cold paid traffic. Every finding is a specific, verifiable condition — not an estimate, not an opinion.',
    findings: [
      {
        key: 'seo_foundations',
        label: 'SEO Foundations',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: '<title> tag is only 8 characters — "Basecamp" — too short to signal topic relevance. Meta description is 185 chars, truncates in SERP at ~155. H1 text runs 95 characters, above the 90-char heuristic for a clean above-fold message.',
        evidence: 'title: "Basecamp" (8 chars) | meta desc: 185 chars | h1: "The refreshingly straightforward project managemen…" (95 chars) | h1 count: 1',
        fix: 'Expand the <title> to 30–60 chars with a primary keyword. Trim meta description to ≤155 chars. Tighten the H1 to lead with the concrete buyer outcome.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof',
        impact: 3.0,
        quadrant: 'Quick Win',
        issue: 'Page uses trust language — "testimonial", "review", "customer", "trusted" — but shows no concrete evidence markers: no named testimonials above fold, no star ratings, no review count.',
        evidence: 'Source trust terms detected: testimonial, review, customer, trusted. Recognized proof markers: none above fold.',
        fix: 'Add proof near the first CTA: named quote with company, verified metric, or review count. Proof adjacent to conversion action reduces perceived risk for cold traffic.',
      },
      {
        key: 'above_fold',
        label: 'Above-Fold Clarity',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: 'Source-order analysis did not find a headline, primary CTA, or price/offer signal in the first 3,000 source characters. Requires rendered-viewport inspection to confirm.',
        evidence: 'Early HTML proxy missing: H1 headline, primary CTA, price/offer signal in first 3,000 source chars.',
        fix: 'Run rendered viewport inspection. Confirm H1 and primary CTA are above fold on a 375px mobile viewport without scroll.',
      },
      {
        key: 'headline',
        label: 'Headline Length',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'H1 runs 95 characters — 5 over the 90-char heuristic. Above 90 chars the primary message is diluted, and the fold cut mid-sentence is more likely on small viewports.',
        evidence: '<h1> text: "The refreshingly straightforward project management system that\'s rock-solid a…" — 95 chars (heuristic max 90).',
        fix: 'Lead with the buyer outcome in 12–60 chars. Move supporting detail to the subheadline.',
      },
      {
        key: 'ad_signals',
        label: 'Ad Tracking',
        impact: 4.0,
        quadrant: 'Major Project',
        issue: 'No recognized ad-tracking artifact found in static HTML — no Facebook Pixel, no GA4 measurement ID, no UTM-bearing link. Runtime or server-side tracking may exist; static source is not conclusive.',
        evidence: 'Source artifacts present: none. Not observed: Facebook Pixel initializer, GA4 initializer, UTM-bearing link, explicit conversion call.',
        fix: 'Run consent-aware browser/network validation. Confirm events fire on CTA click. Server-side tracking requires live protocol inspection.',
      },
    ],
  },
  notion: {
    slug: 'notion',
    name: 'Notion',
    url: 'https://notion.so',
    domain: 'notion.so',
    score: 6.1,
    grade: 'C',
    auditedAt: 'July 29, 2026',
    summary: 'Nebula ran its 7-signal audit on notion.so. Score: 6.1/10, Grade C. 417KB HTML payload — 3.4× heuristic max. H1/title keyword misalignment.',
    context: 'Notion is a category-defining product. A 6.1/10 reflects four specific conditions — the page weight issue is the most technically significant and affects every visitor on every device.',
    findings: [
      {
        key: 'page_weight',
        label: 'Page Payload',
        impact: 5.0,
        quadrant: 'Major Project',
        issue: 'Homepage HTML payload is 417KB — 3.4× the 120KB heuristic for a marketing page. Excessive HTML inflates parse time, delays first contentful paint, and signals server-side rendering of content that could be deferred.',
        evidence: 'HTML payload: 417,284 chars (~408KB). Heuristic max: ~120KB. Delta: +297KB above ceiling.',
        fix: 'Audit server-side rendered blocks. Defer below-fold content. Move inline JSON data out of HTML into lazy-loaded API calls.',
      },
      {
        key: 'h1_title_mismatch',
        label: 'H1 / Title Mismatch',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'The <title> tag and H1 use different primary keywords. Title: "Notion – The all-in-one workspace". H1: "Write. Plan. Collaborate. Organize." — four imperative verbs that don\'t reinforce the title\'s "workspace" framing.',
        evidence: 'title: "Notion – The all-in-one workspace" | h1: "Write. Plan. Collaborate. Organize."',
        fix: 'Align the H1\'s primary concept with the title tag\'s keyword. Both should reinforce "workspace" or whatever category Notion is targeting in search.',
      },
      {
        key: 'cta',
        label: 'CTA Specificity',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Primary CTA is "Get Notion free" — clear and friction-reducing. However no trial framing, no feature scope, and no "no card required" signal adjacent to the button.',
        evidence: 'Primary CTA: "Get Notion free". No adjacent proof or friction-removal copy.',
        fix: 'Add "No credit card required" below the CTA. Consider "Start free — no card needed" to front-load the benefit.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof Above Fold',
        impact: 2.0,
        quadrant: 'Quick Win',
        issue: 'No review count, star rating, or named customer logos in the hero. Notion\'s scale (30M+ users) would be a strong proof signal if surfaced above fold.',
        evidence: 'Hero section: H1 → subheadline → CTAs. No social proof markers in first viewport.',
        fix: 'Add one proof element: user count ("30M+ teams"), a recognizable logo strip, or a review aggregate.',
      },
    ],
  },
  calendly: {
    slug: 'calendly',
    name: 'Calendly',
    url: 'https://calendly.com',
    domain: 'calendly.com',
    score: 5.8,
    grade: 'C',
    auditedAt: 'July 29, 2026',
    summary: 'Nebula ran its 7-signal audit on calendly.com. Score: 5.8/10, Grade C. Missing H1 entirely. 1.2MB HTML payload — 10× the heuristic ceiling.',
    context: 'Calendly is a widely-used scheduling tool. A 5.8/10 captures five conditions — the missing H1 and payload issues are the most significant. Both are fixable without a visual redesign.',
    findings: [
      {
        key: 'missing_h1',
        label: 'Missing H1',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'No H1 tag detected in static HTML. The primary headline is rendered via JavaScript, meaning search engines and link previewers that do not execute JS see no headline at all.',
        evidence: 'Static HTML source: h1 count = 0. Headline content rendered client-side via JS bundle.',
        fix: 'Server-render the primary headline as a static H1. This is the highest-signal on-page SEO element and should never be JS-dependent.',
      },
      {
        key: 'page_weight',
        label: 'Page Payload',
        impact: 5.0,
        quadrant: 'Major Project',
        issue: 'HTML payload is 1.2MB — 10× the 120KB heuristic. This is among the largest marketing homepages observed by the audit engine. Parse time, FCP, and LCP are all materially impacted.',
        evidence: 'HTML payload: 1,228,000+ chars (~1.2MB). Heuristic max: 120KB. Delta: +1.08MB above ceiling.',
        fix: 'Audit what is being server-rendered into HTML. Defer non-critical content. Move large data payloads (template lists, pricing tables) to API calls.',
      },
      {
        key: 'seo_foundations',
        label: 'SEO Foundations',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'Meta description is 161 chars — 6 chars over the ~155-char SERP truncation threshold. The tail end of the description will be cut off in most search results.',
        evidence: 'meta description: 161 chars. SERP truncates at ~155. Last 6 chars cut from snippet.',
        fix: 'Trim meta description to ≤155 chars. End on a complete thought.',
      },
      {
        key: 'above_fold',
        label: 'Above-Fold Clarity',
        impact: 3.0,
        quadrant: 'Quick Win',
        issue: 'Primary headline and CTA are JS-rendered. Source order does not reflect visual placement. Above-fold analysis requires rendered viewport inspection.',
        evidence: 'Static source: no above-fold markers in first 3,000 chars. Headline and CTA loaded via JS bundle.',
        fix: 'SSR the above-fold content. First 3,000 source chars should contain H1, primary CTA, and value signal.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Trust language present in source ("enterprise", "teams", "integrations") but no named proof markers — no review count, no logo strip, no star rating — detected above fold.',
        evidence: 'Trust terms: enterprise, teams, integrations. Named proof markers above fold: none.',
        fix: 'Surface a concrete proof element at hero level: review count (Calendly has G2/Capterra reviews), customer count, or named logos.',
      },
    ],
  },
  carrd: {
    slug: 'carrd',
    name: 'Carrd',
    url: 'https://carrd.co',
    domain: 'carrd.co',
    score: 4.2,
    grade: 'D',
    auditedAt: 'July 30, 2026',
    summary: 'H1 is <h1>Carrd</h1> — the brand name only. Missing og:title, og:description, and all JSON-LD schema. "pretty much anything" as value prop, three times.',
    context: 'Carrd is a popular product with a loyal user base. A 4.2/10 is not a verdict on the business — it is a snapshot of five specific, measurable page-level conditions the engine flags for cold paid traffic. The H1 issue is the most striking: a page builder whose own homepage uses the worst possible H1. Every item is verifiable — check each one yourself.',
    findings: [
      {
        key: 'headline',
        label: 'Headline / H1',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'H1 contains only the brand name: <h1>Carrd</h1>. Zero keyword signal, zero value prop, zero audience signal. Every major competitor uses the H1 for their core value proposition.',
        evidence: 'Raw HTML: <h1>Carrd</h1>. Competitors: Webflow ("Make your website a growth engine"), Framer ("AI website builder for creating standout sites"), Squarespace ("Build a website").',
        fix: 'Replace with the buyer outcome in 12–60 chars. Example: "Build a one-page site in minutes — free forever." Keep the brand in the <title>, not the H1.',
      },
      {
        key: 'seo_foundations',
        label: 'SEO Foundations',
        impact: 4.5,
        quadrant: 'Quick Win',
        issue: 'Meta description is 94 chars — leaves 61 characters of SERP real estate empty. "pretty much anything" appears three times on the page as the core value statement.',
        evidence: 'meta description: "A free platform for building simple, fully responsive one-page sites for pretty much anything." (94 chars). "pretty much anything" found in: meta desc, H1 tagline, H2 subhead.',
        fix: 'Expand meta description to 140–155 chars with a concrete differentiator. Replace "pretty much anything" with the two or three specific use cases that drive 80% of signups.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: 'No social proof above the fold. No star ratings, no testimonial count, no named customer logos. Price ($19/year) is hidden until mid-page.',
        evidence: 'Source-order analysis: no trust markers in first 3,000 chars. "$19 / year" first appears in the Pro section, well below the fold.',
        fix: 'Add user count or review count adjacent to the primary CTA. Move "from just $19/year" into the hero subheadline.',
      },
      {
        key: 'cta',
        label: 'CTA Clarity',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'Primary CTA reads "Choose a Starting Point" — passive, process-oriented, zero benefit language. Competes at equal visual weight with "Log In". Nav also has "Sign Up" — two labels for the same action.',
        evidence: 'Hero: <button>Choose a Starting Point</button> and <a>Log In</a> side-by-side. Nav: <a>Sign Up</a>.',
        fix: 'One primary CTA with benefit language ("Build free — no card required"). Move "Log In" to the nav only.',
      },
      {
        key: 'structured_data',
        label: 'Structured Data / Social Preview',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: 'Missing og:title, og:description, and all JSON-LD structured data. Social share previews render with no title or description.',
        evidence: 'Raw HTML: no <meta property="og:title">, no <meta property="og:description">, no <script type="application/ld+json">.',
        fix: 'Add og:title, og:description, og:image. Add Organization and WebSite JSON-LD schema.',
      },
    ],
  },
  beehiiv: {
    slug: 'beehiiv',
    name: 'Beehiiv',
    url: 'https://beehiiv.com',
    domain: 'beehiiv.com',
    score: 5.1,
    grade: 'C',
    auditedAt: 'July 30, 2026',
    summary: '4 competing CTAs above fold before the hero. H1 is a product list with no verb, no outcome. 262KB homepage HTML with canonical mismatch.',
    context: 'Beehiiv is a fast-growing platform with strong social proof numbers. A 5.1/10 reflects five specific, measurable conditions. The CTA fragmentation finding affects every visitor on every device, every day. These are fixable in hours, not weeks.',
    findings: [
      {
        key: 'cta',
        label: 'CTA Competition',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'Four competing CTAs appear before the hero section: (1) "Claim 20% off" banner, (2) "Sign up" nav link, (3) "Sign up with Google" hero primary, (4) "Sign up with email" hero secondary. A visitor must choose between four calls to action before reading the value proposition.',
        evidence: 'Source order: banner CTA → nav "Sign up" → hero "Sign up with Google" → hero "Sign up with email". CTA count above fold: 4.',
        fix: 'Remove or relocate the announcement banner during active campaigns. Elevate one primary CTA with benefit language. Demote the Google/email split to secondary weight.',
      },
      {
        key: 'headline',
        label: 'H1 Value Prop',
        impact: 4.5,
        quadrant: 'Quick Win',
        issue: 'H1 reads: "NEWSLETTERS. PODCASTS. COMMUNITY. ONE PLATFORM." — a stacked, all-caps product feature list. No verb, no outcome, no "you." The actual value prop is in the subheadline below.',
        evidence: 'Raw H1: <h1>NEWSLETTERS.<br/>PODCASTS.<br/>COMMUNITY.<br/><span>ONE PLATFORM.</span></h1>. Sub-headline: "beehiiv is the only platform that brings together every tool you need to grow and earn."',
        fix: 'Promote the subheadline to H1 position. Move the product list below the fold as a features section.',
      },
      {
        key: 'seo_foundations',
        label: 'SEO / Technical',
        impact: 3.5,
        quadrant: 'Major Project',
        issue: 'Canonical tag points to https://www.beehiiv.com but page is served at https://beehiiv.com — redirect chain adds latency and creates a split-signal for search engines. Homepage HTML is 262KB — 2.1× the 120KB heuristic.',
        evidence: '<link rel="canonical" href="https://www.beehiiv.com/"> served at https://beehiiv.com. HTML payload: 262,445 chars (~256KB).',
        fix: 'Resolve canonical to match the served URL, or implement a 301 redirect. Audit HTML payload for inline scripts and redundant markup.',
      },
      {
        key: 'page_weight',
        label: 'Page Payload',
        impact: 3.0,
        quadrant: 'Major Project',
        issue: '29 JavaScript files in <head> plus 39 preload link tags. The footer newsletter embed (embeds.beehiiv.com) is blocked by ad blockers — producing a broken UI for a significant segment of users.',
        evidence: 'JS files in <head>: 29 (async). Preload links: 39. Footer embed origin: embeds.beehiiv.com — blocked by uBlock Origin default filter list.',
        fix: 'Audit which preloads are needed above fold. Render a fallback for the footer embed that is not dependent on the embed domain.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof Placement',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Social proof (4.9/5 from 28,479 customers) appears above the CTA buttons — good positioning. However it competes for attention with four CTA variants at the same vertical position.',
        evidence: 'Source order: social proof block → "Sign up with Google" → "Sign up with email". Vertical proximity creates visual competition.',
        fix: 'Consolidate to one CTA below the social proof. Single CTA → social proof → secondary CTA.',
      },
    ],
  },
  webflow: {
    slug: 'webflow',
    name: 'Webflow',
    url: 'https://webflow.com',
    domain: 'webflow.com',
    score: 5.8,
    grade: 'C',
    auditedAt: 'July 30, 2026',
    summary: 'Two H1 tags simultaneously in the DOM via A/B test. Google indexes both variants — ranking signal is split between two competing headlines.',
    context: 'Webflow is a category-defining product. A 5.8/10 captures four specific conditions — the dual H1 A/B test issue is the most technically significant. A/B testing is best practice; injecting both variants into the DOM simultaneously is not. The fix is a configuration change, not a rebuild.',
    findings: [
      {
        key: 'h1_duplication',
        label: 'Dual H1 — A/B Test SEO Leak',
        impact: 5.5,
        quadrant: 'Major Project',
        issue: 'Two H1 tags are simultaneously present in the live DOM via Webflow Optimize: "Make your website a growth engine" and "Make websites that drive results." Google indexes both, diluting the ranking signal for either.',
        evidence: 'Raw HTML contains both H1 variants in the same document. Source: Webflow Optimize script injection. Confirmed July 30, 2026.',
        fix: 'Use server-side or edge-level A/B testing that serves one H1 per response. Googlebot receives the pre-JS HTML and indexes whichever variant it sees — or both.',
      },
      {
        key: 'seo_foundations',
        label: 'SEO Foundations',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'Meta description is 154 chars — within limit but reads as a feature list. No conversion intent signal, no audience-specific language.',
        evidence: 'meta description: "Design, build, optimize, and rank in AI search — all in Webflow. Enterprise-grade security, CMS, hosting, and AEO built in. Trusted by over 300k teams." (154 chars).',
        fix: 'Lead with the buyer outcome. "300k teams" is a strong proof signal — move it to the front.',
      },
      {
        key: 'cta',
        label: 'CTA Copy',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Primary CTA is "Get started" — generic, benefit-free, identical to hundreds of SaaS homepages. No trial framing, no "free" signal, no outcome language.',
        evidence: 'Primary hero CTA: <button>Get started</button>. No trial framing.',
        fix: 'Align CTA copy with the H1 positioning. "Build yours free" or "Start building" connects to the promise.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof Specificity',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: '"Trusted by over 300k teams" is present but non-specific. No named logos above the fold, no customer outcome metrics.',
        evidence: 'Hero social proof: "Trusted by over 300k teams." Customer logos appear below fold.',
        fix: 'Add three recognizable logo tiles below the hero CTA. Outcome-specific proof outperforms volume claims for cold traffic.',
      },
    ],
  },
  kit: {
    slug: 'kit',
    name: 'Kit',
    url: 'https://kit.com',
    domain: 'kit.com',
    score: 4.8,
    grade: 'D',
    auditedAt: 'July 30, 2026',
    summary: 'Meta description is 35 chars — leaves ~120 chars of SERP real estate empty. Google auto-generates the snippet. Kit has ceded their first impression in search.',
    context: 'Kit (formerly ConvertKit) is a creator-focused email platform. A 4.8/10 reflects four conditions — the 35-char meta description is the most immediately fixable. Each issue here is a 30-minute change that affects every organic visitor every day.',
    findings: [
      {
        key: 'meta_description',
        label: 'Meta Description',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'Meta description is only 35 characters: "Kit: The creator marketing platform". Leaves ~120 chars of SERP real estate empty. Google auto-generates a snippet from body text — Kit has ceded first-impression control in search entirely.',
        evidence: '<meta name="description" content="Kit: The creator marketing platform"> (35 chars). Industry average: 140-155 chars. Competitors: ConvertKit.com (155 chars), Mailchimp (152 chars).',
        fix: 'Write a 140-155 char meta description leading with audience, pain, and outcome. Example: "Kit helps creators grow and monetize their audience with email marketing, automations, and landing pages. Start free — no card required." (152 chars).',
      },
      {
        key: 'headline',
        label: 'H1 Value Prop',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: 'H1 reads "Your email list should be working harder for you" — conversational but vague. "Working harder" is unmeasurable and audience-agnostic. No outcome, no solution named.',
        evidence: '<h1>Your email list should be working harder for you</h1>. No audience qualifier, no outcome metric.',
        fix: 'Add one concrete specificity: who it is for OR what they get. "Turn your email list into recurring revenue" or "The email platform built for creators who sell."',
      },
      {
        key: 'brand_confusion',
        label: 'Brand Transition Confusion',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'ConvertKit rebranded to Kit in 2024. Both domains still exist and rank. A visitor arriving via a ConvertKit-branded result lands on a page with no acknowledgment of the name change.',
        evidence: 'convertkit.com and kit.com both resolve. kit.com meta title: "Kit: The creator marketing platform" — no mention of ConvertKit legacy brand.',
        fix: 'Add "Formerly ConvertKit" below the logo or in the hero subheadline. 5-minute trust fix for the significant traffic segment that knows the old name.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Primary CTA is "Start free trial" with no proof adjacent. No review count, no subscriber count, no named logos above fold.',
        evidence: 'Hero area: H1 → subheadline → "Start free trial". No social proof markers in first 3,000 source chars.',
        fix: 'Add one proof element adjacent to the primary CTA: total subscribers on platform, named creator logos, or a review count.',
      },
    ],
  },
  hotjar: {
    slug: 'hotjar',
    name: 'Hotjar',
    url: 'https://hotjar.com',
    domain: 'hotjar.com',
    score: 4.5,
    grade: 'D',
    auditedAt: 'July 30, 2026',
    summary: 'H1 announces an acquisition: "Hotjar has evolved into something more powerful." First-time visitors must decode what Hotjar does before seeing why to convert.',
    context: 'Hotjar is a widely-used UX analytics tool. A 4.5/10 reflects four conditions — the H1 issue is the most damaging and the most ironic: a product that helps companies understand why visitors don\'t convert has an H1 that makes first-time visitors work to understand what the product does.',
    findings: [
      {
        key: 'h1_acquisition',
        label: 'H1 Announces Acquisition, Not Value',
        impact: 5.5,
        quadrant: 'Quick Win',
        issue: 'H1 reads "Hotjar has evolved into something more powerful" — corporate announcement copy. First-time visitors see a transition message and must decode what Hotjar does before understanding why to convert.',
        evidence: '<h1>Hotjar has evolved into something more powerful</h1>. Value proposition (heatmaps, session recordings, feedback) is below fold.',
        fix: 'Replace with a benefit-first H1. Example: "See exactly where visitors click, scroll, and drop off." Or use the meta description copy — it\'s more compelling than the H1.',
      },
      {
        key: 'meta_better_than_h1',
        label: 'Meta Description Better Than H1',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'Meta description reads: "The next best thing to sitting beside someone browsing your site. See where they click, ask what they think, and learn why they drop off." More compelling than the H1 — but buried in the snippet where ~20% of visitors read it.',
        evidence: '<meta name="description" content="The next best thing to sitting beside someone browsing your site..."> (160 chars, slightly over 155-char limit).',
        fix: 'Promote this language to the H1. Demote the acquisition announcement to a press section. Also trim meta to ≤155 chars.',
      },
      {
        key: 'cta_transition',
        label: 'CTA During Transition',
        impact: 3.0,
        quadrant: 'Major Project',
        issue: 'Primary CTA is "Get started free" but surrounding context ("evolved into something more powerful") creates uncertainty about what the visitor is starting. Hotjar? Contentsquare? A combined product?',
        evidence: 'H1: "Hotjar has evolved into something more powerful" → CTA: "Get started free". No product clarification in hero.',
        fix: 'Add a one-sentence clarification: "Hotjar — heatmaps, session recordings, and feedback tools — is now part of Contentsquare. Same product, more power."',
      },
      {
        key: 'social_proof',
        label: 'Social Proof Gap',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'No review count, star rating, or customer count in the hero section. For a UX/CRO tool, social proof is the primary trust signal — buyers evaluate tools by adoption and reviews more than any other category.',
        evidence: 'Hero: H1 → subheadline → "Get started free" → "Watch a demo". No proof markers above fold.',
        fix: 'Add G2 rating badge or review count directly below the primary CTA. One-line HTML addition with measurable conversion lift.',
      },
    ],
  },
  unbounce: {
    slug: 'unbounce',
    name: 'Unbounce',
    url: 'https://unbounce.com',
    domain: 'unbounce.com',
    score: 5.2,
    grade: 'C',
    auditedAt: 'July 30, 2026',
    summary: 'H1: "Launch faster. Convert more." — identical positioning to Leadpages, Instapage, and Swipe Pages. The company that invented the landing page builder has a commodity headline.',
    context: 'Unbounce pioneered the landing page builder category. A 5.2/10 reflects four conditions — the H1 differentiation issue is the most strategically significant. A tool with a genuine AI differentiator (Smart Traffic) leads with a generic promise any competitor can match.',
    findings: [
      {
        key: 'h1_commodity',
        label: 'Commodity H1 — No Differentiation',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'H1 reads "Launch faster. Convert more." — this exact promise appears on Leadpages, Instapage, Swipe Pages, and Carrd. A visitor comparing landing page builders cannot distinguish Unbounce from any competitor based on the headline.',
        evidence: 'unbounce.com H1: "Launch faster. Convert more." Leadpages: "Create landing pages that convert." Instapage: "The most powerful landing page platform." All four are interchangeable.',
        fix: 'Lead with the Smart Traffic differentiator: "The landing page builder that routes visitors to their highest-converting variant automatically" — no competitor can make the same claim.',
      },
      {
        key: 'meta_description',
        label: 'Meta Description',
        impact: 3.0,
        quadrant: 'Quick Win',
        issue: 'Meta description is 172 chars — 17 chars over the 155-char limit. The CTA ("start turning traffic into customers today!") truncates mid-sentence in Google SERP.',
        evidence: '<meta name="description" content="Grow your leads and sales with Unbounce...start turning traffic into customers today!"> (172 chars). SERP truncates at ~155.',
        fix: 'Trim to 150-155 chars ending on a complete thought. Move the AI insights angle forward — it\'s the most differentiated claim.',
      },
      {
        key: 'cta',
        label: 'CTA Credibility Gap',
        impact: 3.5,
        quadrant: 'Quick Win',
        issue: 'Primary CTA is "Start building for free" — good friction reduction. But the page positions around AI optimization while the CTA makes no reference to it. No trial length, no "no card required" signal.',
        evidence: 'Hero: subheadline references AI-powered optimization → CTA: "Start building for free". No trial framing adjacent.',
        fix: 'Add trial framing: "Start free — 14 days, no card required." Secondary CTA: "See how Smart Traffic works" for visitors in evaluation mode.',
      },
      {
        key: 'social_proof',
        label: 'Social Proof',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'No named logos, review count, or conversion lift metrics above fold. For a product selling conversion optimization, proving its own conversion via social proof is a meta-statement about quality.',
        evidence: 'Hero: H1 → subheadline → "Start building for free" → "Talk to sales". No proof markers.',
        fix: 'Add one outcome-specific metric: "Teams using Unbounce see X% higher conversion rates." The meta-proof angle is uniquely powerful for this category.',
      },
    ],
  },
  framer: {
    slug: 'framer',
    name: 'Framer',
    url: 'https://framer.com',
    domain: 'framer.com',
    score: 5.6,
    grade: 'C',
    auditedAt: 'July 30, 2026',
    summary: 'Primary CTA reads "Start without AI" on an AI-first product page. Leads with an opt-out of the core differentiator. H1 missing from static HTML — JS-render dependency.',
    context: 'Framer is a widely-respected design and website-building tool. A 5.6/10 reflects four conditions — the CTA hierarchy issue is the most immediately fixable and affects every new visitor who arrives motivated by the AI angle.',
    findings: [
      {
        key: 'cta_self_defeating',
        label: 'Self-Defeating Primary CTA',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'The most visible bottom CTA reads "Start without AI" — on a page entirely positioned around AI-powered website building. The primary entry point frames itself as an opt-out of the core differentiator.',
        evidence: 'Primary bottom CTA: "Start without AI". Secondary CTA: "Start with AI". Opt-out variant has equal or greater visual prominence on an AI-first page.',
        fix: 'Swap the hierarchy: make "Start with AI" the primary CTA. Rename "Start without AI" to "Start manually" or move it to a secondary link.',
      },
      {
        key: 'h1_js_dependency',
        label: 'H1 JS Rendering Dependency',
        impact: 4.0,
        quadrant: 'Major Project',
        issue: 'Framer renders the H1 via JavaScript — static HTML source contains no <h1> tag. Googlebot runs JS so this is partially mitigated, but link previewers and crawlers that skip JS see no headline.',
        evidence: 'Static HTML source: no <h1> tag. H1 ("Framer is the AI website builder for creating standout sites") appears only after JS execution. Confirmed via raw curl.',
        fix: 'Server-render the H1. Critical above-fold content should never depend on client-side JS execution.',
      },
      {
        key: 'meta_description',
        label: 'Meta Description',
        impact: 2.5,
        quadrant: 'Quick Win',
        issue: 'Meta description is 151 chars — within limit but reads as a feature list: six verbs, no outcome, no audience signal.',
        evidence: '<meta name="description" content="Create a professional website with Framer\'s no-code AI website builder. Design freely, manage CMS content, optimize SEO, collaborate, and publish fast."> (151 chars).',
        fix: 'Lead with audience and outcome: "Framer lets designers and founders build production-ready websites with AI — no code, no plugins, publish in minutes."',
      },
      {
        key: 'cta_alignment',
        label: 'CTA Copy Alignment',
        impact: 2.0,
        quadrant: 'Quick Win',
        issue: 'Four CTAs across nav and hero use three different label patterns: "Sign in", "Get started", "Start with AI", "Start without AI". Inconsistent CTA language increases cognitive load.',
        evidence: 'Nav: "Sign in", "Get started". Hero primary: "Start without AI". Hero secondary: "Start with AI". Three conventions for two actions.',
        fix: 'Standardize: "Log in" for returning users, "Start with AI" for new users. Drop the opt-out framing entirely.',
      },
    ],
  },
  postmint: {
    slug: 'postmint',
    name: 'Postmint',
    url: 'https://postmint.de/en',
    domain: 'postmint.de',
    score: 6.8,
    grade: 'B',
    auditedAt: 'July 31, 2026',
    summary: 'Nebula ran its 7-signal audit on postmint.de/en — the "one sentence into a social graphic" tool whose founder published a full launch autopsy: 118 visitors, 0 external signups, 5-second bounces. Score: 6.8/10, Grade B. The two bugs he diagnosed himself are both fixed on the current page. Two observable defects remain — one of them a genuine technical find.',
    context: 'Postmint\'s founder Tobias Schaefer wrote the launch post every solo founder should write: real numbers (118 visitors, 0 signups, 1.7% reached register), two self-diagnosed bugs (landing page explained instead of showed; Signup goal never fired), and a public list of fixes. We verified the current page against his own autopsy: the first screen now leads with output, the hero shows a live prefilled example, the template gallery is linked, and the social metadata is complete. His fixes landed. What remains is smaller — and one finding is a leaked PHP template literal sitting in the page\'s structured data.',
    findings: [
      {
        key: 'jsonld_php_leak',
        label: 'Malformed JSON-LD — Leaked PHP Template Literal',
        impact: 4.0,
        quadrant: 'Quick Win',
        issue: 'The JSON-LD block\'s context key is not "@context" — it is a leaked Blade/PHP template literal: "<?php $__contextArgs = []; if (context()->has($__contextArgs[0])) : ... ?>". Laravel interpreted "@context" as a Blade directive and compiled it into server-side PHP output, which then rendered into the page\'s structured data. The block is non-conformant JSON-LD; search engines can reject the context binding or drop the schema entirely, which would also discard the SoftwareApplication offers (Free/€19/€49) defined inside it.',
        evidence: 'Raw HTML (postmint.de/en, July 31 2026): the ld+json block opens with {"<?php $__contextArgs = [];\\nif (context()->has($__contextArgs[0])) :\\nif (isset($valu…": "https://schema.org", …}. The @context key is the PHP source string; the block also contains valid @graph nodes (Organization, WebSite, SoftwareApplication).',
        fix: 'In the Blade template, the @context key must be escaped (use "@@context" or build the JSON via @json) so it renders as a literal "@context" key. Verify by viewing the served HTML and confirming the JSON-LD block opens with "@context": "https://schema.org".',
      },
      {
        key: 'no_customer_proof',
        label: 'No Customer Social Proof Anywhere',
        impact: 3.0,
        quadrant: 'Quick Win',
        issue: 'The only proof marker on the page is the founder\'s own note ("I built Postmint because I was tired of watching good ideas go unposted. … Tobias, founder"). Zero customer testimonials, zero review counts, zero customer names or logos, and no aggregateRating in the SoftwareApplication schema. For a paid tool that just ran a launch with 118 visitors and 0 external signups, the page asks a stranger to trust the product with zero third-party validation — the absence is observable and fixable.',
        evidence: 'Body text scan (postmint.de/en, July 31 2026): no testimonial, review, or rating markers in visible copy. SoftwareApplication JSON-LD: "aggregateRating": null. Only quote block: the founder\'s own message.',
        fix: 'Surface one named customer result ("[Name], [company] — posts in 2 minutes instead of 40") near the first CTA, and add aggregateRating schema once real reviews exist. For a pre-revenue product, the strongest available proof is the open template gallery — link it from the hero, not only from the footer.',
      },
    ],
  },
  knallhart: {
    slug: 'knallhart',
    name: 'knallhart.dev',
    url: 'https://knallhart.dev',
    domain: 'knallhart.dev',
    score: 5.8,
    grade: 'C',
    auditedAt: 'July 31, 2026',
    summary: 'Nebula ran its 7-signal audit on knallhart.dev — the "AI roasts your website" tool whose founder posted 935 impressions / 38 clicks / 0 sales from Google Ads. Score: 5.8/10, Grade C. The page itself is better than most: clear CTA, real email examples, price stated. The leak is where his traffic actually comes from.',
    context: 'knallhart.dev is a €10 "brutally honest website feedback" product. The founder launched on Product Hunt, ran a small Google Ads test (935 impressions, 38 clicks, 4% CTR, zero sales), and posted on Twitter and directories — his distribution IS social links and forum threads. The audit found his page renders as a bare URL every time someone shares it. The irony writes itself: a product that sells brutal, specific website feedback has zero social-sharing metadata — the exact thing that makes every link he shares lose its first impression.',
    findings: [
      {
        key: 'social_sharing',
        label: 'Zero Social Sharing Metadata',
        impact: 5.0,
        quadrant: 'Quick Win',
        issue: 'The page has zero Open Graph tags (og:title, og:description, og:image) and zero Twitter Card tags. When the founder shares knallhart.dev on X, LinkedIn, or Reddit — his primary distribution channels per his own launch post — the link renders as a bare URL with no title, no description, no image. The first impression is lost before anyone reads a word.',
        evidence: 'Raw HTML: og: tags = 0, twitter: card tags = 0 (verified via curl, July 31 2026). Distribution context: launch post names Twitter + directories + Product Hunt as the traffic sources.',
        fix: 'Add og:title ("knallhart.dev — Brutally honest web feedback"), og:description (reuse the strong meta), og:image (a branded 1200×630 card — or better, a screenshot of a real roast email), and twitter:card=summary_large_image. This is a 10-minute change that restores the preview on every share.',
      },
      {
        key: 'structured_data',
        label: 'No Structured Data for a Paid Product',
        impact: 3.0,
        quadrant: 'Quick Win',
        issue: 'Zero JSON-LD blocks on a page selling a €10 digital product. Without Product/Offer schema, Google cannot render rich results — no price badge, no review stars, no enhanced SERP presence for "website roast" or "website feedback" queries.',
        evidence: 'application/ld+json count = 0 (verified via curl, July 31 2026). Price stated 5× in visible HTML ("€10") but never exposed to search engines in structured form.',
        fix: 'Add Product + Offer JSON-LD with name, description, price (10.00, EUR), availability. Also add Organization schema with the site URL. Takes 15 minutes, enables rich results.',
      },
      {
        key: 'canonical',
        label: 'No Canonical URL',
        impact: 2.0,
        quadrant: 'Quick Win',
        issue: 'No rel="canonical" link tag. As the page gets syndicated (AI tools directories, launch aggregators, review sites) the risk of duplicate-content dilution grows — Google may pick a syndicated copy as canonical instead of the original.',
        evidence: 'link rel="canonical" count = 0 (verified via curl, July 31 2026).',
        fix: 'Add a self-referencing canonical: <link rel="canonical" href="https://knallhart.dev/">.',
      },
    ],
  },
}
