import type { Meta, StoryObj } from '@storybook/nextjs'
import Breadcrumb from '@/app/components/Breadcrumb'
const meta = { title: 'Tier 3/Breadcrumb', component: Breadcrumb, tags: ['autodocs'], parameters: { nextjs: { navigation: { pathname: '/resources/citable' } }, docs: { description: { component: 'Visible responsive breadcrumb trail with auto-generated route labels, UUID handling, custom items, and matching JSON-LD.' } } } } satisfies Meta<typeof Breadcrumb>
export default meta
type Story = StoryObj<typeof meta>
export const AutoGenerated: Story = {}
export const CustomItems: Story = { args: { items: [{ name: 'Resources', url: '/resources' }, { name: 'Citable', url: '/resources/citable' }] } }
