var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/mpp/audit-compat/route.js")
R.c("server/chunks/node_modules_viem_1e_g98x._.js")
R.c("server/chunks/lib_x402_ts_0yytvd1._.js")
R.c("server/chunks/[root-of-the-server]__1gkk4op._.js")
R.c("server/chunks/[root-of-the-server]__0dun8c5._.js")
R.c("server/chunks/node_modules_0o_o3uc._.js")
R.c("server/chunks/[root-of-the-server]__15bjnu5._.js")
R.c("server/chunks/node_modules_0qok5vf._.js")
R.c("server/chunks/_next-internal_server_app_api_mpp_audit-compat_route_actions_00c-mho.js")
R.m(71278)
module.exports=R.m(71278).exports
